// config.h is generated by cmake while build freetype-gl from template config.h.in by cmake variable status

#define FREETYPE_GL_USE_GLEW 0
/* #undef FREETYPE_GL_USE_VAO */
/* #undef GL_WITH_GLAD */

#if defined _WIN32 || defined _WINDOWS
#include <Windows.h>
#endif
